<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-6HGP4Q4" name="services.Login" tests="7" failures="1" timestamp="12 May 2020 18:46:36 GMT" time="8.380" errors="0">
  <testcase name="emptyEmail" time="0.756" classname="services.Login"/>
  <testcase name="emptyEmailEmptyPassword" time="0.784" classname="services.Login"/>
  <testcase name="validEmailInvalidPassword" time="1.875" classname="services.Login"/>
  <testcase name="loginWithDeactivatedUser" time="1.471" classname="services.Login"/>
  <testcase name="ValidFepUserLogin" time="1.817" classname="services.Login">
    <failure type="java.lang.AssertionError" message="expected [0] but found [-2]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [-2]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at services.Login.loginBase(Login.java:72)
at services.Login.ValidFepUserLogin(Login.java:81)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- ValidFepUserLogin -->
  <testcase name="InvalidEmail" time="0.926" classname="services.Login"/>
  <testcase name="validEmailEmptyPassword" time="0.751" classname="services.Login"/>
</testsuite> <!-- services.Login -->
